name: build-ubuntu-release

# build on pushes and pull requests on main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x64] #architecture: [x86, x64]
        build-platform: [x64] #build-platform: [x86, x64]

    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v4

    - name: Update apt repositories & install deps
      run: |
        sudo apt update
        sudo apt-get install cmake g++-12 gcc-12 ninja-build
<<<<<<< Updated upstream
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave
=======
>>>>>>> Stashed changes

    - name: Ensure deps are installed
      run: |
        cmake --version
        g++ --version
        ninja --version

    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -GNinja -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12
        ninja
